// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sytivyecoqsmpvitgzja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5dGl2eWVjb3FzbXB2aXRnemphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjEyNTQsImV4cCI6MjA2MDk5NzI1NH0.qDAd-93ltEZ3ZGhVJHuTzWiFzgV46rQ-v7Lo0OSFgNQ.7R6w-QDEubIkdMOKDQmMg7khZ308cJRO41S-UvkNp60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);