// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://setmmwbkbzggiupijjwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNldG1td2JrYnpnZ2l1cGlqandtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzk2MjMsImV4cCI6MjA1OTc1NTYyM30.7R6w-QDEubIkdMOKDQmMg7khZ308cJRO41S-UvkNp60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);