// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pumlaeokluqmsspzqorq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1bWxhZW9rbHVxbXNzcHpxb3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDM1MTMsImV4cCI6MjA2MTIxOTUxM30.MsVWWF4sJg5nr69ER8hTdsbeUutSj1Vx0pN5CTN9CRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);